display:
  default:
    display_options:
      filters:
        langcode:
          expose:
            label: Teanga
  default_page:
    display_options:
      fields:
        edit_media:
          text: 'Cuir in eagar'
  page:
    display_options:
      fields:
        edit_media:
          text: 'Cuir in eagar'
        delete_media:
          text: Scrios
